### ISSUE TITLE
build-ships with topoff doesn't work right

### ISSUE THREAD

**Issue by Imzogelmo** [nataliethistime/le-serf#105]
I haven't studied exactly what it's doing, but it will say that more ships exist than really do, and then try to build more than you actually have space to build. So I'd suspect some parameters are getting confused.

**Comment by nataliethistime** [comment]
I've noticed this myself recently. I'll give this a look soon-ish.

**Comment by nataliethistime** [comment]
I'm gonna try fix this today.

**Comment by nataliethistime** [comment]
Oh yeah. I fixed this.
